"""
Central keyword list for PrintTender India.
Used by all fetchers and the Celery scheduler.
"""

PRINT_KEYWORDS: list[str] = [
    # ── Owner's product list (English) ─────────────────────────────────
    "calendars",
    "diary",
    "sticker",
    "registers",
    "books",
    "forms",
    "papers",
    "note books",
    "brochures",
    "flyers",
    "visiting cards",
    "certificates",
    "receipt books",
    "prospectus",
    "catalogues",
    "pass books",
    "duplex box",
    "cards",
    "answer books",
    "exercise books",
    "tags",
    "posters",
    "banners",
    "labels",
    "desk pads",
    "envelopes",
    "marks sheet",
    "stationary",
    "note sheets",
    "files",
    "pamphlets",
    "annual reports",
    "souvenir",
    # ── Hindi transliterations (for CPPP / state portal searches) ───────
    "पंचांग",
    "डायरी",
    "स्टिकर",
    "रजिस्टर",
    "पुस्तक",
    "प्रपत्र",
    "कागज",
    "नोटबुक",
    "ब्रोशर",
    "पर्चा",
    "विजिटिंग कार्ड",
    "प्रमाण पत्र",
    "रसीद बुक",
    "विवरणिका",
    "सूची पत्र",
    "पासबुक",
    "कार्ड",
    "उत्तर पुस्तिका",
    "अभ्यास पुस्तिका",
    "टैग",
    "पोस्टर",
    "बैनर",
    "लेबल",
    "लिफाफा",
    "अंक तालिका",
    "स्टेशनरी",
    "फाइल",
    "वार्षिक प्रतिवेदन",
    "स्मारिका",
    # ── Common government tender search terms ───────────────────────────
    "offset printing",
    "digital printing",
    "security printing",
    "government forms printing",
    "textbook printing",
    "gazette printing",
    "ballot paper",
    "toner cartridge",
    "packaging printing",
    "label printing",
    "flex printing",
    "screen printing",
    "letterpress",
    "book binding",
    "lamination",
]

# Alias kept for backwards compatibility
PRINTING_KEYWORDS = PRINT_KEYWORDS
