export const PORTAL_OPTIONS = [
  "MP Tenders",
  "eproc.mp.gov.in",
  "CPPP",
  "gem.gov.in",
  "PNB Tenders",
  "Canara Bank Tenders",
  "Central Bank of India Tenders",
  "Bank of India Tenders",
  "Indian Bank Tenders",
  "UCO Bank Tenders",
  "Indian Overseas Bank Tenders",
  "LIC Tenders",
  "MP PWD",
  "MPBSE",
  "MP Forest",
  "MP Info",
  "State-MP",
  "State-UP",
  "Maharashtra Tenders",
  "State-RJ",
  "TenderDekho",
  "BidAssist",
  "Dainik Bhaskar",
  "Nai Dunia",
  "Patrika",
  "Dainik Jagran",
  "Nav Bharat",
  "Deshbandhu",
  "Raj Express",
  "Peoples Samachar",
  "Dabang Dunia",
  "Free Press Journal",
  "Pradesh Today",
  "Agniban",
  "Nav Swadesh",
  "Swadesh",
  "Amar Ujala",
  "TOI Tenders",
  "HT Tenders",
  "ET Tenders",
  "The Hindu Tenders",
  "Tender Notice India",
  "India Tender Notice",
  "Public Notice India",
];

