export const PORTAL_OPTIONS = [
  "MP Tenders",
  "eproc.mp.gov.in",
  "CPPP",
  "gem.gov.in",
  "PNB Tenders",
  "Canara Bank Tenders",
  "Central Bank of India Tenders",
  "Bank of India Tenders",
  "Indian Bank Tenders",
  "UCO Bank Tenders",
  "Indian Overseas Bank Tenders",
  "LIC Tenders",
  "MP PWD",
  "MPBSE",
  "MP Forest",
  "MP Info",
  "State-MP",
  "State-UP",
  "Maharashtra Tenders",
  "State-RJ",
  "TenderDekho",
  "BidAssist",
];
